version: '3'

services:
  app:
    build: .
    container_name: online-banking-api
    restart: always
    volumes:
      - .:/app
    expose:
      - "3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      HTTP_PORT: ${HTTP_PORT}
    depends_on:
      db:
        condition: service_healthy
  web:
    image: nginx
    container_name: online-banking-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - db
  db:
    image: postgres
    container_name: online-banking-db
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql/online_banking:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGUSER: "${POSTGRES_USER}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
  migrate-post:
    image: migrate/migrate
    container_name: online-banking-migrate
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@online-banking-db:5432/${POSTGRES_DATABASE}?sslmode=disable",
        "up"
      ]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
volumes:
  db:
  migrations:
